# try:
#     num = 1
#     print(num)
# except:
#     print('发生错误....')
# finally:
#     print('finally')

# try:
#     # num = 1
#     print(num)
# except:
#     print('发生错误....')
# else:
#     print('else')
# finally:
#     print('finally')


# try:
#     # num = 1
#     print(num)
# finally:
#     print('finally')